name: Build NativeScript Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        app: ['angular', 'core-js', 'core-ts', 'react', 'svelte', 'vue']

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install Python
        uses: actions/setup-python@v1

      - name: Install NativeScript
        run: |
          python -m pip install --upgrade pip six
          npm i -g nativescript --ignore-scripts
          tns usage-reporting disable
          tns error-reporting disable
          tns doctor
          
      - name: Install Dependencies
        run: npm ci
        working-directory: apps/${{ matrix.app }}
      
      - name: Build Android Application
        run: tns build android --copy-to dist/${{ matrix.app }}.apk
        working-directory: apps/${{ matrix.app }}
      
      - name: Build iOS Application
        run: tns build ios --copy-to dist/${{ matrix.app }}.ipa
        working-directory: apps/${{ matrix.app }}
      
      - name: Upload Builds
        uses: actions/upload-artifact@v1
        with:
          name: Builds
          path: ./apps/${{ matrix.app }}/dist
